# Generated by Django 3.0.3 on 2021-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HmisStatePw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('tot_no_pw_reg_anc', models.IntegerField(blank=True, null=True)),
                ('no_early_anc_register', models.IntegerField(blank=True, null=True)),
                ('early_anc_register', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_anc_4_or_more', models.IntegerField(blank=True, null=True)),
                ('anc_4_or_more', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_tt1', models.IntegerField(blank=True, null=True)),
                ('pw_tt1_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_tt2', models.IntegerField(blank=True, null=True)),
                ('pw_tt2_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_tt_booster', models.IntegerField(blank=True, null=True)),
                ('pw_tt_booster_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_calcium', models.IntegerField(blank=True, null=True)),
                ('pw_calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_ifa', models.IntegerField(blank=True, null=True)),
                ('pw_ifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_pw_given_albendazole', models.IntegerField(blank=True, null=True)),
                ('pw_albendazole', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tot_c_section_deliveries', models.IntegerField(blank=True, null=True)),
                ('c_section_deliveries', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'hmis_state_pw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HmisStChldDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('tot_chld_born', models.IntegerField(blank=True, null=True)),
                ('chld_disease_pneumonia', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_pneumonia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_sepsis', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_sepsis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_tb', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_tb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_malaria', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_malaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_diarrhoea', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_diarrhoea', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_diarrhoea_trtd_inpatnt', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_diarrhoea_trtd_inpatnt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_admtd_upper_resp_infec', models.IntegerField(blank=True, null=True)),
                ('per_chld_admtd_upper_resp_infec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_disease_sam', models.IntegerField(blank=True, null=True)),
                ('per_chld_disease_sam', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'hmis_st_chld_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HmisStChldImmunzt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('tot_chld_born', models.IntegerField(blank=True, null=True)),
                ('chld_immunzt_vit_k1', models.IntegerField(blank=True, null=True)),
                ('per_chld_immunzt_vit_k1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_immunzt_bcg', models.IntegerField(blank=True, null=True)),
                ('per_chld_immunzt_bcg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_immunzt_9to11m_mr', models.IntegerField(blank=True, null=True)),
                ('per_chld_immunzt_9to11m_mr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_immunzt_9to11m_measl_1st_dose', models.IntegerField(blank=True, null=True)),
                ('per_chld_immunzt_9to11m_measl_1st_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chld_immunzt_vit_a_dose_1', models.IntegerField(blank=True, null=True)),
                ('per_chld_immunzt_vit_a_dose_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_chld_12to59m_albendazole', models.IntegerField(blank=True, null=True)),
                ('per_no_chld_12to59m_albendazole', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'hmis_st_chld_immunzt',
                'managed': False,
            },
        ),
    ]
